// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Request struct {
	ID               int64
	TraceID          string
	SessionKey       *string
	ClientID         *string
	Ts               time.Time
	Format           string
	Provider         string
	Model            string
	AliasUsed        *string
	RoutingRationale string
	Domain           *string
	Effort           *string
	CostClass        *string
	Confidence       *float64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	CostUsd          float64
	LatencyMs        int64
	StatusCode       int64
	Error            *string
	Stream           bool
	ToolCallsJson    *string
}
