// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"
)

const insertRequest = `-- name: InsertRequest :one
INSERT INTO requests (
    trace_id, session_key, client_id, ts, format, provider, model,
    alias_used, routing_rationale, domain, effort, cost_class, confidence,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
    cost_usd, latency_ms, status_code, error, stream, tool_calls_json,
    config_epoch
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertRequestParams struct {
	TraceID          string
	SessionKey       *string
	ClientID         *string
	Ts               time.Time
	Format           string
	Provider         string
	Model            string
	AliasUsed        *string
	RoutingRationale string
	Domain           *string
	Effort           *string
	CostClass        *string
	Confidence       *float64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	CostUsd          float64
	LatencyMs        int64
	StatusCode       int64
	Error            *string
	Stream           bool
	ToolCallsJson    *string
	ConfigEpoch      *string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRequest,
		arg.TraceID,
		arg.SessionKey,
		arg.ClientID,
		arg.Ts,
		arg.Format,
		arg.Provider,
		arg.Model,
		arg.AliasUsed,
		arg.RoutingRationale,
		arg.Domain,
		arg.Effort,
		arg.CostClass,
		arg.Confidence,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostUsd,
		arg.LatencyMs,
		arg.StatusCode,
		arg.Error,
		arg.Stream,
		arg.ToolCallsJson,
		arg.ConfigEpoch,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recentRequests = `-- name: RecentRequests :many
SELECT id, trace_id, provider, model, cost_usd, latency_ms, status_code, ts, config_epoch
FROM requests
ORDER BY ts DESC
LIMIT ?
`

type RecentRequestsRow struct {
	ID          int64
	TraceID     string
	Provider    string
	Model       string
	CostUsd     float64
	LatencyMs   int64
	StatusCode  int64
	Ts          time.Time
	ConfigEpoch *string
}

func (q *Queries) RecentRequests(ctx context.Context, limit int64) ([]RecentRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentRequestsRow
	for rows.Next() {
		var i RecentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Provider,
			&i.Model,
			&i.CostUsd,
			&i.LatencyMs,
			&i.StatusCode,
			&i.Ts,
			&i.ConfigEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
